### ISSUE TITLE
Points do not add up

### ISSUE THREAD

**Issue by JZ3007** [MakotoE/guess-the-eval#5]
Floating point values not getting rounded resulting in errors by more than one point aside, there is a mistake in calculation of points given within PointsSolver.ts. Not sure if this is the only error in the calculation, but code on line 45:
` const unadjusted = -8 * (1 / Math.abs(0.5 * correctEval + 1))
      * Math.abs(guessEval - correctEval)
      + 50;`
 does not match the equation in the comments on line 9:
 `points = -8(1/abs(0.5c + 1))d^2 + 50`
This results in [absurd point calculation](https://imgur.com/a/mEQJeCh)

**Comment by MakotoE** [comment]
Fixed with https://github.com/MakotoE/guess-the-eval/commit/4cf9f3600ff3788d169af0d7ff1af8a8f4bf22fe. I can't believe I didn't catch this before. Thanks for the issue. The fact that the question order gets randomized for each game made it confusing to differentiate database (constant) order and game (randomized) order. Now the game ordered questions are saved to an array.

**Comment by MakotoE** [comment]
I changed the scoring equation, including the code, so that it is now `points = -8(1/abs(0.5c + 1))d^1.5 + 50`. The `^1.5` determines how much to decrease the score for being off. Hopefully this makes it more fun but not too punishing.
