### ISSUE TITLE
Guessing the best move with a negative score multiplies the penalty + odd maths

### ISSUE THREAD

**Issue by sylverdrag** [MakotoE/guess-the-eval#6]
Just ran into this issue: 

Position displayed seemed to allow for checkmate, so I rated +20 (there should be a way to indicate a checkmate in the eval). However, there was a defensive resource I missed which turned the position into a draw, so the actual eval was +0.15. The score was about -20.
 
The best move was obvious so I got that right, earning myself a 3x multiplier... so the question was scored -53. 

It doesn't make sense that finding the best move would cause the outcome to be 3x worse, nor does it make sense that 3 x -20 results in -53 (didn't guess the players either). 

It would make more sense to score only with positive integers (no matter how wrong you are on a question, it shouldn't negate points obtained on other questions), and finding the right move shouldn't make things worse.

**Comment by cinnabasil** [comment]
What about maybe if instead of removing negative scores entirely, getting a 3x multiplier divides your negative score by 3? so instead of -20, you get -6 (or -7) score? Just a thought

**Comment by MakotoE** [comment]
Thanks for sharing your experience. When I was designing the scoring system, I intentionally made it so that it is possible to get negative points. But as you pointed out (pun intended), if there is high uncertainty in the eval, it is too easy to get a very negative score. [On this line](https://github.com/MakotoE/guess-the-eval/blob/4cf9f3600ff3788d169af0d7ff1af8a8f4bf22fe/src/PointsSolver.ts#L49), you can see that a negative score is adjusted by dividing by 4 to reduce the effect of a negative score. Perhaps we could divide by a higher number.

**Comment by MakotoE** [comment]
@morrigan-plus-plus That's a great idea. I'll have to think about it.

**Comment by MakotoE** [comment]
When I first designed the scoring system, I intentionally made it so that getting the correct move multiplies a negative score, just because I think it is hilarious. But the actual experience can be different. If getting a multiplier divides your negative score, it would have an opposite effect than my original idea. But that might provide the best end experience.
